### ISSUE TITLE
Restrictor Plate Settings.

### ISSUE THREAD

**Issue by pskerrett** [andrewsil1/UltrastikCmd#1]
Hi,

I just installed a restrictor plate on my Ultrastik, and am trying to configure the device to allow me to get the full signal level out with the plate on. IE, prior to the plate, I was getting axis signals of about 32,000 using jstest for /dev/input/js0

Now I'm getting 16,000 which makes sense, but analog control based games are not fully functional.

I have ultrastikcmd compiled & functional, but am not sure how to use this to tell the stick that it has a restrictor installed. 

pi@retropie:~ $ sudo ultrastikcmd -c 1 -v
Write to flash: No
Use restrictor: No
Border locations::
 0x1e  0x3a  0x56  0x72  0x8e  0xaa  0xc6  0xe2
device identification of HIDInterface 001/007[2]:
  dev_handle:    0x019fa9b8
  device:        0x019f4530
  location:      001/007
  manufacturer:  Ultimarc UltraStik
  product:       Ultimarc Ultra-Stik Player 1
  serial number: 1
Bind-driver request sent to the kernel

There is a '-o' command that says 'use restrictor' which works initially - 

Report bugs to andrewsi@outlook.com.
pi@retropie:~ $ sudo ultrastikcmd -c 1 -o -v
Write to flash: No
Use restrictor: Yes
Border locations::
 0x1e  0x3a  0x56  0x72  0x8e  0xaa  0xc6  0xe2
device identification of HIDInterface 001/007[2]:
  dev_handle:    0x0124d9b8
  device:        0x01247530
  location:      001/007
  manufacturer:  Ultimarc UltraStik
  product:       Ultimarc Ultra-Stik Player 1
  serial number: 1
Bind-driver request sent to the kernel

But that value does not get saved:

pi@retropie:~ $ sudo ultrastikcmd -c 1 -v
Write to flash: No
Use restrictor: No
Border locations::
 0x1e  0x3a  0x56  0x72  0x8e  0xaa  0xc6  0xe2
device identification of HIDInterface 001/007[2]:
  dev_handle:    0x014ba9b8
  device:        0x014b4530
  location:      001/007
  manufacturer:  Ultimarc UltraStik
  product:       Ultimarc Ultra-Stik Player 1
  serial number: 1
Bind-driver request sent to the kernel

How do I program this into a map file or something to allow it to save?

Thanks.

**Comment by andrewsil1** [comment]
I'm not sure if putting the restrictor info in a map file was ever supported, you may simply have to always include the parameter when reprogramming different maps.  I'll be able to look at this a little closer later this week to confirm.

Sent from Outlook Mobilehttps://aka.ms/djubve

On Sun, Apr 10, 2016 at 11:50 AM -0700, "Patrick Skerrett" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

I just installed a restrictor plate on my Ultrastik, and am trying to configure the device to allow me to get the full signal level out with the plate on. IE, prior to the plate, I was getting axis signals of about 32,000 using jstest for /dev/input/js0

Now I'm getting 16,000 which makes sense, but analog control based games are not fully functional.

I have ultrastikcmd compiled & functional, but am not sure how to use this to tell the stick that it has a restrictor installed.

pi@retropie:~ $ sudo ultrastikcmd -c 1 -v
Write to flash: No
Use restrictor: No
Border locations::
0x1e 0x3a 0x56 0x72 0x8e 0xaa 0xc6 0xe2
device identification of HIDInterface 001/007[2]:
dev_handle: 0x019fa9b8
device: 0x019f4530
location: 001/007
manufacturer: Ultimarc UltraStik
product: Ultimarc Ultra-Stik Player 1
serial number: 1
Bind-driver request sent to the kernel

There is a '-o' command that says 'use restrictor' which works initially -

Report bugs to andrewsi@outlook.commailto:andrewsi@outlook.com.
pi@retropie:~ $ sudo ultrastikcmd -c 1 -o -v
Write to flash: No
Use restrictor: Yes
Border locations::
0x1e 0x3a 0x56 0x72 0x8e 0xaa 0xc6 0xe2
device identification of HIDInterface 001/007[2]:
dev_handle: 0x0124d9b8
device: 0x01247530
location: 001/007
manufacturer: Ultimarc UltraStik
product: Ultimarc Ultra-Stik Player 1
serial number: 1
Bind-driver request sent to the kernel

But that value does not get saved:

pi@retropie:~ $ sudo ultrastikcmd -c 1 -v
Write to flash: No
Use restrictor: No
Border locations::
0x1e 0x3a 0x56 0x72 0x8e 0xaa 0xc6 0xe2
device identification of HIDInterface 001/007[2]:
dev_handle: 0x014ba9b8
device: 0x014b4530
location: 001/007
manufacturer: Ultimarc UltraStik
product: Ultimarc Ultra-Stik Player 1
serial number: 1
Bind-driver request sent to the kernel

How do I program this into a map file or something to allow it to save?

Thanks.

##

**Comment by pskerrett** [comment]
Thanks Andrew, let me know what you find. I'm curios to see what the function of the -o flag is ...

If you wouldn't mind giving a quick overview of how to write a restrictor-enabled map, that would be much appreciated.

THanks.

**Comment by andrewsil1** [comment]
After reviewing the code, the -o flag simply passes the parameter to the stick to indicate that there is a restrictor in place.  It may be the case that by using the write-to-flash option, that information will be remembered, so you should try that out.  If that doesn't work, then simply use the -o option every time you use the utility to send a new map file to the stick.

There is no support in the map file format to indicate that a restrictor is in place, so the command line parameter is the only way to communicate this information to the stick.
